version: 2.1
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:tap-tester
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            python3 -m venv /usr/local/share/virtualenvs/tap-pagerduty
            source /usr/local/share/virtualenvs/tap-pagerduty/bin/activate
            pip install -U 'pip==21.1.3'
            pip install 'setuptools==69.0.3'
            pip install .[dev]
      - run:
          name: 'pylint'
          command: |
            source /usr/local/share/virtualenvs/tap-pagerduty/bin/activate
            make test

workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user
